### ISSUE TITLE
Separating the GUI from the Editor

### ISSUE THREAD

**Issue by leeola** [felixangell/phi#93]
Having just found out about Phi I'm quite interested in using it as a GUI based for some ideas floating around in my head, namely to have a GUI frontend for various editor backends such as Neovim.

With that said, I don't want to put work into the API and/or GUI features towards my goals, if they conflict with the projects goals. Namely in that the GUI would have to be able to support generic features _(multiple cursors, cursor(s) positions, gutter characters, font colors, popups, splits, etc)_ without being explicitly bound to the existing editor implementation. Editors would then be able to indicate basic GUI commands _(set cursor/etc)_ without knowledge of the actual editor backend.

Does this sound compatible with this project? cc @felixangell

**Comment by felixangell** [comment]
You know I've considered separating the GUI into its own library and using that for this project. An interesting idea but probably quite cumbersome, and the current code for the editor is a bit messy and is due some refactoring/re-writing.

Though, I'm not really sure what you are proposing/asking here.

**Comment by leeola** [comment]
I was mostly just asking if it was inline with the projects goals to support this separation between editor and GUI. Sounds like it is, though a bit of work is needed. Ie, if I were to submit PRs related to my goals, I'd want to make sure they were inline with your own as well. I'm surveying options atm between different projects, writing my own, etc.

Thanks for your thoughts on the subject :)

**Comment by felixangell** [comment]
I see. 

Though it depends since I might not want to make the API for the GUI components too generalised if it could complicate the implementation of the editor.
